<?php
T("table-group-works","کارهای دسته جمعی");
T("table-data-count","تعداد یافته ها");
T("paging-prev","قبلی");
T("paging-next","بعدی");
T("table-paging-goto","برو به");
T("table-row-counter","ردیف");
T("table-page-size","سایز صفحه");
T("table-submit","اعمال");
T("table-filter-title","فرم فیلتر");
T("table-filter-btn-submit","اعمال فیلتر");
T("table-filter-btn-clear","حذف فیلتر ");
T("table-filter-btn-plus","جدید");
T("select","انتخاب");
T("select-all","انتخاب همه");
T("list","لیست");
T("close","بستن");
T("cancel","انصراف");
T("edit","ویرایش");
T("detail","جزئیات");
T("delete","حذف");
T("ok","تایید");
T("history-log","تاریخچه تغییرات");
T("back","بازگشت");
T("print","چاپ");
T("save_export","ذخیره سربرگ");
T("submit","اعمال");
T("anything","هیچکدام");
T("sum","جمع");
T("report-excel","خروجی اکسل");
T("report-csv","خروجی csv");
T("setting-print-col","ستون ها");
T("setting-print-font","فونت");
T("setting-print-font-size","سایز نوشته ها");
T("report-print","چاپ اطلاعات");
T("delete-title","حذف اطلاعات");
T("detail-title","جزئیات");
T("print-title","تنظیمات چاپ");
